# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build ${{ github.ref }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Fetch deps
        run: yarn --mutex network --frozen-lockfile --network-concurrency 25 --silent --disable-self-update-check

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            docs
            flow-typed
            target
            typings
            package.json
          retention-days: 1
  push:
    name: Push ${{ github.ref }}
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      checks: read
      statuses: write
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.ref == 'refs/heads/master' && '0' || '1' }}

      - uses: actions/download-artifact@v4
        with:
          name: build

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Fetch deps
        run: yarn --mutex network --frozen-lockfile --network-concurrency 25 --silent --disable-self-update-check

      - name: Run tests
        run: yarn test

      - name: Codeclimate
        if: github.ref == 'refs/heads/master'
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/target/coverage/lcov.info:lcov

      - name: Semantic Release
        if: github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PROVENANCE: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
        run: npm_config_yes=true npx zx-semrel

  pr:
    name: PR (Node v${{ matrix.node-version }}, OS ${{ matrix.os }})
    if: github.event_name == 'pull_request'
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-24.04, windows-latest ]
        node-version: [ 16, 22 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Fetch deps
        run: yarn --mutex network --frozen-lockfile --network-concurrency 25 --silent --disable-self-update-check --ignore-engines

      - name: Run tests
        run: yarn test
